instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    properties:
      jenkins:
        admin:
          email: buildtools@finkit.com
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: ((jenkins_server_url))
    release: jenkins
  name: jenkins-master
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  - jenkins-pool
  vm_type: default
- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: jenkins-slave
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
          type: build
    release: jenkins
  name: jenkins-slave
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
        developer:
          password: ((nexus_developer_password))
    release: nexus
  name: nexus
  networks:
  - name: default
  persistent_disk_pool: 500GB
  stemcell: default
  vm_extensions:
  - internet-required
  - nexus-pool
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    properties:
      sonar:
        admin:
          password: ((sonar_admin_password))
    release: sonarqube
  name: sonarqube
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - sonar-pool
  vm_type: default
name: buildstack
os: ubuntu-trusty
releases:
- name: jenkins
  sha1: 4e60fcbb79e5f2e9ae5f06612f287542781f2409
  url: https://storage.googleapis.com/dev-build-automate-release-tarballs/jenkins-boshrelease/jenkins-boshrelease-v0.0.60.tgz
  version: 0.0.60
- name: nexus
  sha1: 1658e6f386ad8543c6440aa3b99afff7de47908e
  url: https://storage.googleapis.com/dev-build-automate-release-tarballs/nexus-boshrelease/nexus-boshrelease-v1.0.10.tgz
  version: 1.0.10
- name: sonarqube
  sha1: d56a3fe87aa1176728904de9db65c71bd413002f
  url: https://storage.googleapis.com/dev-build-automate-release-tarballs/sonarqube-boshrelease/sonarqube-boshrelease-v0.0.40.tgz
  version: 0.0.40
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3586.25"
update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000
variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password
- name: nexus_developer_password
  type: password
- name: sonar_admin_password
  type: password
- name: sonar_mysql_password
  type: password

